-- Oracle

SELECT NAME||'('||SUBSTR(OCCUPATION, 0, 1)||')'
FROM OCCUPATIONS 
ORDER BY NAME;


SELECT 'There are a total of '||CNT||' '||JOB||'s.' 
FROM ( 
    SELECT lower(OCCUPATION) JOB, count(OCCUPATION) AS CNT
    FROM OCCUPATIONS
    GROUP BY OCCUPATION
)
ORDER BY CNT, JOB;